import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  padded: { padding: 20 },
  appTitle: { fontSize: 52, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 14 },
  loginCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 20,
    padding: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  loginTitle: { fontSize: 22, fontWeight: "bold", marginBottom: 4 },
  loginSubtitle: { fontSize: 13, marginBottom: 24 },
  mainButton: {
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 12,
  },
  buttonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },
  roleBtn: { flex: 1, padding: 12, borderRadius: 10, alignItems: "center" },
  input: {
    padding: 13,
    borderRadius: 10,
    marginBottom: 12,
    fontSize: 14,
    justifyContent: "center",
  },
  guardNameLarge: { fontSize: 26, fontWeight: "bold", marginBottom: 4 },
  guardDetail: { fontSize: 13, marginTop: 2 },
  guardName: { fontSize: 15, fontWeight: "600" },
  onDutyBadge: {
    backgroundColor: "#22C55E",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    marginVertical: 12,
  },
  onDutyText: { color: "#FFFFFF", fontWeight: "bold", fontSize: 13 },
  timerCard: {
    width: "100%",
    padding: 24,
    borderRadius: 18,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  timerLabel: { fontSize: 11, letterSpacing: 2 },
  countdownTimer: { fontSize: 56, fontWeight: "bold" },
  shiftInfoText: { marginTop: 8, fontSize: 13 },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  kpiGrid: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  kpiCard: {
    width: "23%",
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 22,
    marginBottom: 20,
    minHeight: 170,
    alignItems: "center",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  kpiLabel: {
    fontSize: 18,
    marginTop: 10,
    textAlign: "center",
    fontWeight: "600",
  },
  kpiValue: {
    fontSize: 42,
    fontWeight: "700",
  },
  card: {
    borderRadius: 16,
    padding: 28,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: { fontSize: 22, fontWeight: "bold", marginBottom: 16 },
  alertItem: {
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
  },
  alertGuardName: { fontWeight: "700", fontSize: 16 },
  alertTime: { fontSize: 13, marginTop: 2 },
  userCard: {
    borderRadius: 16,
    padding: 24,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  statusBadgeText: { fontSize: 10, fontWeight: "600" },
  actionColumn: { marginLeft: 10, gap: 8 },
  actionBtn: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  actionBtnText: { color: "#FFFFFF", fontSize: 12, fontWeight: "600" },
  rowSpace: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  alertBanner: {
    paddingHorizontal: 40,
    paddingVertical: 20,
    borderRadius: 20,
    marginBottom: 16,
  },
  alertBannerText: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
  },
  countdown: { fontSize: 64, fontWeight: "bold" },
  countdownSub: { marginBottom: 20, fontSize: 13 },
  gameContainer: { alignItems: "center", marginVertical: 20 },
  gameHint: { fontWeight: "600", marginBottom: 16, textAlign: "center" },
  pongArena: {
    width: 300,
    height: 220,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  primaryButton: {
    padding: 14,
    borderRadius: 12,
    marginVertical: 6,
    alignItems: "center",
    width: 200,
  },
  dpadBtn: {
    width: 48,
    height: 48,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
  },
  dpadText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  modalContainer: {
    borderRadius: 20,
    padding: 24,
    width: "92%",
    maxWidth: 420,
  },
  modalTitle: { fontSize: 19, fontWeight: "bold", marginBottom: 16 },
  modalLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  modalBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 4,
  },
  languageToggle: {
    flexDirection: "row",
    borderRadius: 20,
    padding: 3,
    marginBottom: 16,
  },
  langBtn: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 18 },
  langBtnActive: { backgroundColor: "#3B82F6" },
  langText: { fontWeight: "600", fontSize: 12 },
  adminHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  hamburgerBtn: { padding: 8 },
  hamburgerText: { fontSize: 22, fontWeight: "bold" },
  adminHeaderTitle: { fontSize: 22, fontWeight: "bold" },
  adminContent: { flex: 1 },
  sidebarOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 50,
  },
  sidebar: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: 280,
    zIndex: 100,
    elevation: 10,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
  },
  sidebarHeader: {
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
    marginBottom: 8,
  },
  sidebarItem: {
    paddingVertical: 13,
    paddingHorizontal: 24,
    marginHorizontal: 8,
    borderRadius: 10,
    marginBottom: 2,
  },
  sidebarItemText: { fontSize: 14, fontWeight: "500" },
  pageHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
  },
  pageHeaderTitle: { fontSize: 24, fontWeight: "700" },
  pageHeaderSub: { fontSize: 12, marginTop: 2 },
  createBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10 },
  createBtnText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  tableCard: {
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 20,
  },
  tableHeaderRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  tableHeaderCell: { fontSize: 10, fontWeight: "700", letterSpacing: 0.8 },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderTopWidth: 1,
  },
  tableRowPrimary: { fontSize: 16, fontWeight: "600" },
  tableRowSecondary: { fontSize: 13, marginTop: 1 },
  emptyRow: { padding: 32, alignItems: "center" },
  siteIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  countBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  countBadgeText: { fontSize: 12, fontWeight: "700" },
  sitePill: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  sitePillText: { fontSize: 12, fontWeight: "600" },
  tblEditBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 7,
    borderWidth: 1,
    alignItems: "center",
  },
  tblEditBtnText: { fontSize: 11, fontWeight: "600" },
  tblDeleteBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 7,
    alignItems: "center",
  },
  tblDeleteBtnText: { fontSize: 13 },
  filterPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
  },
  filterPillText: { fontSize: 12, fontWeight: "600" },
  pickerField: {
    padding: 13,
    borderRadius: 10,
    marginBottom: 12,
    fontSize: 14,
    justifyContent: "center",
    borderWidth: 1,
    ...Platform.select({
      web: {
        height: 48,
        paddingVertical: 0,
      },
      default: {},
    }),
  },
});
